project:
  type: website
  resources:
    - images
website:
  title: ""
  site-url: "https://g0lft.org"
  favicon: images/favicon.ico
  navbar:
    left:
      - text: Home
        href: index.qmd 
      - text: Station
        href: station.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Blog
        href: blog.qmd
    right:
      - text: Contact
        href: contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



